name:        sandy-mcquire-freer-monads-in-action-eff
version:     0.0.1.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >= 4.7 && < 5
- freer
- HUnit
- monad-logger
- mtl
- test-hunit-util
- transformers

library:
  source-dirs: src
