Created       : 2013 Aug 21 (Wed) 14:54:35 by carr.
Last Modified : 2014 Jan 08 (Wed) 21:20:34 by Harold Carr.

------------------------------------------------------------------------------
* CABAL INSTALLS

cabal update
cabal install cabal-install
- [[https://groups.google.com/forum/#!topic/haskell-cafe/SFoNwaq8wdc]]
cd /Library/Haskell/bin
sudo mv cabal.real cabal.real-1.16
sudo ln -s ~/Library/Haskell/bin/cabal cabal.real
sudo chown carr cabal.real

cd ~/.sync/.esync/java/org/openhc/test-hunit-util
make configure build install

cabal install aeson
cabal install hlint
cabal install primes
cabal install hsparql
cabal install hoogle
hoogle data

# install Pandoc, Haykll, ...
cd ~/.sync/sites/haroldcarr.com/
cabal install

TODO
cabal install lhs2tex

------------------------------------------------------------------------------
* CABAL SANDBOXES

- [[http://coldwa.st/e/blog/2013-08-20-Cabal-sandbox.html]]

I do not want the sandbox contents copied when syncing via CrashPlan, unison, get, etc.
And I do not want to tell each of them to ignore.
Instead I have a special place to put all sandboxes and then link to them.

mkdir ~/CABAL-SANDBOXES

cd ~/.sync/ftptmp/ebooks-music-pics/tech
git clone git@github.com:robstewart57/hsparql.git
cd ~/.sync/ftptmp/ebooks-music-pics/tech/hsparql
cabal sandbox init
cabal install --only-dependencies
cabal build

mkdir ~/CABAL-SANDBOXES/hsparql
mv .cabal-sandbox  ~/CABAL-SANDBOXES/hsparql
mv cabal.sandbox.config ~/CABAL-SANDBOXES/hsparql
# TODO: this expands ~ - so not portable
ln -s ~/CABAL-SANDBOXES/hsparql sandbox
ln -s sandbox/.cabal-sandbox
ln -s sandbox/cabal.sandbox.config
# temporary measure : I did sandbox before HC
ln -s /Volumes/HC /Volumes/untitled

ln -s ~/ftptmp/ebooks-music-pics/tech/programming-language/haskell/interview/s.hs

# DONE
cabal sandbox delete


------------------------------------------------------------------------------
* WHEN UPGRADING GHC

install all previously installed packages
some might not install, in which case delete from ~/.cabal/world and run again
and install them again later when they are working again with that version of ghc.

cabal install world

# End of file.

