name:         th-playground
version:      0.0.1.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >=4.11 && < 5
- template-haskell

library:
  source-dirs: src

_exe-ghc-options:        &exe-ghc-options
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  main:
    source-dirs:         app
    main:                Main.hs
    ghc-options:         *exe-ghc-options
    dependencies:
      - th-playground

tests:
  test:
    source-dirs:         test
    main:                hspec.hs
    ghc-options:         *exe-ghc-options
    dependencies:
      - th-playground
      - hspec
