resolver: lts-13.25
packages:
- .
extra-deps:
- git: git@github.com:haroldcarr/test-hunit-util.git
  commit: 17971cdff83473fe044c7ea82aade2ed6afc47ed
# flags: {}
# extra-package-dbs: []
# require-stack-version: -any # Default
# require-stack-version: ">=2.1"
# arch: i386
# arch: x86_64
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
# compiler-check: newer-minor
