# Created       : 2014 Apr 17 (Thu) 16:01:09 by Harold Carr.
# Last Modified : 2014 Apr 27 (Sun) 08:23:20 by Harold Carr.

clean ::
	rm *.vrb *.aux *.log *.nav *.out *.snm *.tex *.toc

# End of file.

