#!/bin/bash

HERE="${BASH_SOURCE%/*}"
. ${HERE}/base.sh

msgN "--------------------------------------------------"
doone 1 tx-no-forward?TX11
doone 2 tx-no-forward?TX21
doone 2 tx-no-forward?TX22
doone 3 tx-no-forward?TX31

lbl "2-txs"
lbl "all peers get txs, store and forward to peers"
msg "1: TXPool=[TX11];      Chain=[GB]"
msg "2: TXPool=[TX21,TX22]; Chain=[GB]"
msg "3: TXPool=[TX31];      Chain=[GB]"
doall state
