#!/bin/bash

HERE="${BASH_SOURCE%/*}"
. ${HERE}/base.sh

msgN "--------------------------------------------------"
doone 1 tx-no-forward?TX31
doone 1 tx-no-forward?TX21
doone 1 tx-no-forward?TX22
doone 2 tx-no-forward?TX11
doone 3 tx-no-forward?TX11
doone 3 tx-no-forward?TX21
doone 3 tx-no-forward?TX22

lbl "3-after-txs"
lbl "all txs received (except TX31 not at peer 2)"
msg "1: TXPool=[TX11,TX31,TX21,TX22]; Chain=[GB]"
msg "2: TXPool=[TX21,TX22,TX11]     ; Chain=[GB]"
msg "3: TXPool=[TX31,TX11,TX21,TX22]; Chain=[GB]"
doall state
