#!/bin/bash

HERE="${BASH_SOURCE%/*}"
. ${HERE}/base.sh

msgN "--------------------------------------------------"
lbl "1-initial"
msg "1: TXPool=[]; Chain=[GB]"
msg "2: TXPool=[]; Chain=[GB]"
msg "3: TXPool=[]; Chain=[GB]"

doall state
