#!/bin/bash

HERE="${BASH_SOURCE%/*}"
. ${HERE}/base.sh

msg "==== TOY ===="

msg "--------------------------------------------------"
msg "node 2 creates/sends TX1 to peers"
doone 2 tx?TX1
msg "all nodes should have TX1 in TXPool"
doall state

msg "--------------------------------------------------"
msg "node 3 mines a block and adds  to its Chain"
doone 3 mine
msg "node 3 should have the new block with TX1 in Chain and nothing in TXPool."
msg "peers should still have TX1 in their TXPool"
doall state
msg "node 3 'broadcasts' its new block to peers"
doone 1 resolve
doone 2 resolve
msg "all peers should be in same state with TX1 in Chain and nothing in TXPool."
doall state

msg "--------------------------------------------------"
msg "node 1 creates/sends TX3 to peers"
done 2 tx-no-forward?


#doone 0 tx-no-forward?TX2
#doall mine
#sleep 2
#section "after doall mine"
#doall env
#
#doone 1 tx-no-forward?TX3
#doone 1 mine
#sleep 2
#section "at this point the heights should be 0:2 1:3; 0 should have TX1 TX2 in its chain; 1 should have TX1 TX3 in its chain"
#doall env
#
#doone 0 resolve
#section "0 should have 1's chain; *but it should have TX2 in its pool*"
#doall env

