name:                vittorio-aaccaria-dependent-pairs
version:             0.1.0.0

ghc-options:
- -Wall
- -fwarn-redundant-constraints

dependencies:
- base >= 4.7 && < 5
- singletons

library:
  source-dirs: .
