name:        type-level-chris-penner
version:     0.0.1.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >=4.11 && < 5
- random
- servant
- text
- uuid

library:
  source-dirs: src

