name:                justin-le-fixed-length-vector-types
version:             0.1.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >= 4.7 && < 5
- finite-typelits
- hspec
- singletons
- vector

library:
  source-dirs: src

_exe-ghc-options:        &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  m:
    source-dirs:         app
    main:                Main.hs
    ghc-options:         *exe-ghc-options
    dependencies:
    - justin-le-fixed-length-vector-types

tests:
  t:
    source-dirs:         test
    main:                hspec.hs
    ghc-options:         *exe-ghc-options
    dependencies:
    - hspec
    - justin-le-fixed-length-vector-types
