name:                justin-le-intro-to-singletons
version:             0.1.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >= 4.7 && < 5
- ghc-prim
- hspec
- HUnit
- singletons
- test-hunit-util

library:
  source-dirs: src
