name:                nikolay-yakimov-intro-to-free-monads
version:             0.1.0.0

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >= 4.7 && < 5
- free
- transformers

library:
  source-dirs: src

_exe-ghc-options:        &exe-ghc-options
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

executables:
  main:
    source-dirs:         app
    main:                Main.hs
    ghc-options:         *exe-ghc-options
    dependencies:
    - nikolay-yakimov-intro-to-free-monads

tests:
  test:
    source-dirs:         test
    main:                Spec.hs
    ghc-options:         *exe-ghc-options
    dependencies:
    - nikolay-yakimov-intro-to-free-monads
