name:         htmx
version:      0.0.1.0
synopsis:     htmx
description:  See README at <https://github.com/htmx/htmx
author:       htmx
github:       htmx/htmx
category:     htmx

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints
- -fhide-source-paths

dependencies:
- base >=4.11 && < 5
- scotty
- wai-cors
- wai-extra

library:
  source-dirs: src

_exe-ghc-options:        &exe-ghc-options
- -threaded
- -rtsopts
- -with-rtsopts=-N

executables:
  main:
    source-dirs:         app
    main:                Main.hs
    ghc-options:         *exe-ghc-options
    dependencies:
      - htmx
