#!/bin/bash

HERE="${BASH_SOURCE%/*}"
. ${HERE}/base.sh

msg "==== 4-three-mines-block-A3B ===="
doone 3 mine

msg "1 : TXPool=[TX11,TX31,TX21,TX22]; Chain=[GB]"
msg "2 : TXPool=[TX21,TX22,TX11]     ; Chain=[GB]"
msg "3 : TXPool=[]                   ; Chain=[GB, {TX31,TX11,TX21,TX22}]"
doall state
