#!/bin/bash

HERE="${BASH_SOURCE%/*}"
. ${HERE}/base.sh

msg "==== 5 after A3B  ===="

doone 1 resolve
doone 2 resolve

msg "--------------------------------------------------"
msg "1 : TXPool=[]; Chain=[GB, {TX31,TX11,TX21,TX22}]"
msg "2 : TXPool=[]; Chain=[GB, {TX31,TX11,TX21,TX22}]"
msg "3 : TXPool=[]; Chain=[GB, {TX31,TX11,TX21,TX22}]"
doall state
