#!/bin/bash

HERE="${BASH_SOURCE%/*}"
. ${HERE}/base.sh

msg "==== 6-tx31-arrives  ===="

doone 2 tx-no-forward?tx31

msg "--------------------------------------------------"
msg "1 : TXPool=[]    ; Chain=[GB, {TX31,TX11,TX21,TX22}]"
msg "2 : TXPool=[TX31]; Chain=[GB, {TX31,TX11,TX21,TX22}]"
msg "3 : TXPool=[]    ; Chain=[GB, {TX31,TX11,TX21,TX22}]"
doall state
