resolver: lts-13.25
packages:
- .
extra-deps:
- refined-0.4.4@sha256:7dbbb741e397c61dc68a9c1d891b711344f8f1543f099bf012b54360a44a9ca0,2916
# flags: {}
# extra-package-dbs: []
# system-ghc: true
# require-stack-version: -any # Default
# require-stack-version: ">=2.1"
# arch: i386
# arch: x86_64
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
# compiler-check: newer-minor
